// <auto-generated />
#pragma warning disable IDE0079 // Dont remove next line
#pragma warning disable IDE0005, CS8019 // Dont remove global usings

global using static CloudFiles.Troubleshooter.Consts;
global using static Spectre.Console.AnsiConsole;
global using static Windows.Win32.PInvoke;

using System.Diagnostics;

using Windows.Win32.Storage.CloudFilters;

namespace CloudFiles.Troubleshooter
{
	delegate int CommandHandler(ReadOnlySpan<string> args);

	static unsafe class Consts
	{
		public static CF_CALLBACK_REGISTRATION[] NoneCallbackRegistration = [
			new() { Type = CF_CALLBACK_TYPE.CF_CALLBACK_TYPE_NONE, Callback = null }
		];

		public static string UsageFormat = $"Usage: {Process.GetCurrentProcess().ProcessName} {{0}} {{1}}";
	}
}
